version: 0.2

artifacts:
  type: zip
  files:
    - 'utils.py'
    - 'application.py'
    - 'dialogue_manager.py'
    - 'intentClassifierEN'
    - 'intentClassifierEN.py'
    - 'intentClassifierFR'
    - 'intentClassifierFR.py'
    - 'requirements.txt'
    - 'tfidfVectorizerfr'
    - 'tfidfVectorizeren'